### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by s3ththompson**
Adding a `CONTRIBUTING.md` file to document our policy around accepting issues and PRs from the community.

### CODE REVIEW

**Comment by alflennik** [comment]
Apologies for the build error! That will occur until https://github.com/w3c/aria-at-app/pull/352 is merged. Once that PR is merged, we can merge this one.

**Comment by alflennik** [comment]
Also Seth could you make the base of the PR main instead of develop? I think the consensus is to use the GitHub Flow branching strategy, and for that one we don't need to use a develop branch.

**Comment by alflennik** [comment]
I took care of that! :)

**Comment by s3ththompson** [comment]
I should change `develop` to `main` right?

**Comment by alflennik** [comment]
I did that Seth, after Jes reviews we should be good to merge.

**Review by jesdaigle — APPROVED** [review]

**Pull request merged**
