### PR TITLE
Remove nodegit dependency

### PR DESCRIPTION
**Pull request by alflennik**
Removes nodegit which requires a lot of C compilation to work and often fails - in favor of using the git present in the environment.

### CODE REVIEW

**Comment by evmiguel** [comment]
@alflennik The new build config for nodegit with Node 18 can be removed now: https://github.com/w3c/aria-at-app/pull/484/files#diff-fcc964e27d1e22339051a8ce39304eb2c721e3d96ab72d9fb20b4a2192f74b60

**Comment by alflennik** [comment]
Oh okay thanks @evmiguel, is that from line 11 to 18 on .github/workflows/runtest.yml?

**Comment by evmiguel** [comment]
> Oh okay thanks @evmiguel, is that from line 11 to 18 on .github/workflows/runtest.yml?

Yes, that's it!

**Comment by alflennik** [comment]
@evmiguel thanks for remembering that change, it's fixed!

**Review by evmiguel — APPROVED** [review]

**Pull request merged**
