### PR TITLE
Accessibility fixes for combobox and disclosures

### PR DESCRIPTION
**Pull request by howard-e**
Addresses #429.

This PR moves away from using bootstrap's `<Form.Control as="select" />` which used the native HTML `select` widget for a user to select possible values from a list. In it's place, a [combobox](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/) has been implemented which is based on the [Combobox APG Select Only Example](https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-select-only.html).

Additionally, the robustness of the disclosure components used with the `ManageTestQueue` component and `Run History` on relevant reporting pages has been improved.

### CODE REVIEW

**Comment by jscholes** [comment]
@howard-e This is significantly concerning.  The APG's select-only combobox pattern does not work with macOS Safari, so unless steps have been taken to address that, the PR will exclude macOS testers and admins.  It's also the case that the native `<select>` has good accessibility for single-select cases, and it would have potentially been less disruptive to fix whatever the problems were with the mark-up than implementing a new component from scratch.

**Comment by howard-e** [comment]
Thanks for raising that concern @jscholes. I did address the issues I found when with testing on Safari, but after another brief test, I've found another edge case. Will draft until additional use cases have been exhausted.

**Comment by jscholes** [comment]
@howard-e How have you fixed the Safari issues?

**Comment by howard-e** [comment]
> @howard-e How have you fixed the Safari issues?

A big one (that I've just noticed was accidentally stashed) was forcing focus to the last selected listbox option when the "openKeys" were used to avoid the issue of the listbox not being focused with keys which weren't 'ArrowDown'. Then keeping that focus looped within the listbox when the VO combinations to navigate was used, until closed. But even then, there still appears to be some caveats  with the navigation and feedback (aria-labels were used due to lack of feedback in some cases).

Thanks again for the feedback @jscholes. The implementation still appears to be quite brittle and I think it would make more sense for me to iterate on it and contribute to APG should I get it into a better state for review.

> @jscholes said: 
It's also the case that the native `<select>` has good accessibility for single-select cases, and it would have potentially been less disruptive to fix whatever the problems were with the mark-up

Agreed, will be closing this PR and addressing the feedback concerns of #429 with the native `<select>`.

The disclosure accessibility fixes included in this PR have already been pulled into #432.

**Pull request closed without merging**
