### PR TITLE
Move Candidate Phase Start Date and Target Completion Date into dedicated columns on Candidate Tests page

### LINKED ISSUE #727: Candidate test page: Remove Change Target Date button, Move Candidate Phase Start Date and Target Completion Date, change title (P1)
In Candidate test page : 

- [x] Move Candidate Phase Start Date and Target Completion Date out of test plan column into separate columns.
- [x] Change page title from "Candidate Tests" to "Candidate Review"

### PR DESCRIPTION
**Pull request by stalgiag**
This PR does the following:

- [x] Move Candidate Phase Start Date and Target Completion Date out of test plan column into separate columns.
- [x] Change page title from "Candidate Tests" to "Candidate Review"

Note that I did not change the route name in order to preserve any indexing. It is still `/candidate-tests`. I can change it if desired.

resolves #727 

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205204111609719

### CODE REVIEW

**Review by alflennik — CHANGES_REQUESTED** [review]
Importantly, would you mind changing the url to `candidate-review` as well?

Less important, but still important, I was wondering if you would be able to rename the components and code which refer to "Candidate Tests" as opposed to Candidate Review. That kind of blows up the size of the PR unfortunately but I think it's worth it just to reduce the amount of mental overhead tracking the "old name" of the feature.

The main feature of the PR, moving the dates to their own columns, worked great for me. Nice.

**Comment by stalgiag** [comment]
Think I got everything! I renamed every conceptually related use of `Candidate Tests` and changed the route.

**Review by alflennik — APPROVED** [review]
Thank you, looks great!! After Howard reviews I feel good to merge.

**Review by howard-e — APPROVED** [review]
Looks good to me! Thanks @stalgiag and @alflennik!

**Pull request merged**
