### PR TITLE
Implement Test Navigator Toggle button as Disclosure Widget

### PR DESCRIPTION
**Pull request by jkva**
This PR addresses the following item from PAC's "ARIA-AT App Screen Reader Accessibility Observations" document:

> Directly after the "Test Navigator" heading, there is a button which reads: "Toggle button to close test navigator". This label is overly verbose, and points to the fact that a Disclosure pattern is not being used (e.g. as demonstrated by the APG's example of disclosures for a navigation menu). This control would be far more usable as a button with aria-expanded, collapsed down into the previous heading. That is, the heading should wrap a button inside it, labelled "Test Navigator", which programmatically indicates its expanded/collapsed state via aria-expanded. As an aside, that will also give the button a visible label because the heading is on-screen; right now the button only has an icon.

@jscholes some duplication exists in #362. The `h2` around the `button` is now used to describe the `ol` inside the `nav`, but is not itself a child of the `nav` since it is its toggle control. This does not follow the usual pattern of placing the heading in the nav ahead of the nav list, but another specific heading seems overkill. Thoughts?

--- 

Effective changes:

- Wrap a `h2` around toggle `button`;
- set a static `aria-label` onto the `button`;
- manage `aria-expanded` attribute on the `button`;
- associate `button` with `nav` using `aria-controls` idref; and
- describe navigation list using `h2`.

### CODE REVIEW

**Review by jscholes — CHANGES_REQUESTED** [review]
@jkva I agree with pretty much all of this; it's a nice compromise between discoverability and polluting the page (e.g. with a nav region that only contains a collapsed button by default).

Only one thing: `aria-label="Test Navigator"` should really be `aria-label="Test Navigation"`, so that it fits with the "Test navigation" that users will hear when they expand it and access the labelled `nav`.

**Comment by jkva** [comment]
@jscholes thanks for catching that. I found some redundant class and CSS usage - removed that to simplify while I was at it.

**Review by jscholes — APPROVED** [review]

**Comment by alflennik** [comment]
Once the conflicts are resolved, we feel ready to merge this!

**Comment by jkva** [comment]
@alflennik The PR has been rebased onto `main` and the conflict has been resolved.

**Pull request merged**
