### PR TITLE
Render status list within manage bot run dialog

### PR DESCRIPTION
**Pull request by jugglinmike**
Partially resolves gh-872 ~~(I do not have access to JAWS, and since the reported problem does not occur with VoiceOver, I cannot verify this fix)~~ (I erroneously included the prior text; please ignore it.)

### CODE REVIEW

**Review by howard-e — APPROVED** [review]
Code looks good to me!

I do feel the gaps of vertical space in the dialog are a little bit much. Could they be trimmed? Approving though because I don't feel strongly on this, and in the absence of explicit visual requirements or mockups, my thought on this is purely opinion.

**Comment by jugglinmike** [comment]
Thanks for the review, @howard-e. I'm happy to oblige your design preference; I just need a little clarification. [That padding is applied to all instances of this app's modal dialog.](https://github.com/w3c/aria-at-app/blob/eaf9109add8d8d2df8939fdbdd1f536f26ac7be1/client/components/TestRun/TestRun.css#L461-L465) Would you prefer to see an override for this instance, or would you like the padding reduced everywhere?

**Comment by howard-e** [comment]
> Thanks for the review, @howard-e. I'm happy to oblige your design preference; I just need a little clarification. [That padding is applied to all instances of this app's modal dialog.](https://github.com/w3c/aria-at-app/blob/eaf9109add8d8d2df8939fdbdd1f536f26ac7be1/client/components/TestRun/TestRun.css#L461-L465) Would you prefer to see an override for this instance, or would you like the padding reduced everywhere?

Reducing them everywhere feels good to me. But I wonder what other's thoughts on it may be.

This has now also made me notice that unnecessary padding gets added in a lot of instances for `modal-footer` even though that content is not populated as much. With that in mind, I think this overall design concern should be tied to another issue and not be included in this PR.

**Comment by jugglinmike** [comment]
Thanks, @howard-e! Here's an issue to track the design work: https://github.com/w3c/aria-at-app/issues/907

**Pull request merged**
