### PR TITLE
Redirect a GitHub user when they are not in an authorized group

### PR DESCRIPTION
**Pull request by evmiguel**

### CODE REVIEW

**Comment by spectranaut** [comment]
Hey Erika I'm not sure how to test this -- I changed the teams in config/dev.env to point back to the bocoup teams so I could completely take myself off of them. Then I logged and logged in, but the log in was successful, I just could only see the "Settings" and "reports" page.

**Comment by evmiguel** [comment]
@spectranaut I made a new GitHub user and tried to log in with the new user credentials.

**Comment by spectranaut-test** [comment]
Works like a charm! :)

**Review by spectranaut — APPROVED** [review]
Works like a charm!

**Pull request merged**
